// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAmF1eF-eOJzOviCVdJK0PgWkZQJQCmkY',
    appId: '1:537714219373:web:b16b76fdc778580acd6264',
    messagingSenderId: '537714219373',
    projectId: 'safegas001',
    authDomain: 'safegas001.firebaseapp.com',
    storageBucket: 'safegas001.firebasestorage.app',
    measurementId: 'G-69VB96V50Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFvPUb7VSITdZ6qMwtSnc-AvaZoudIF_g',
    appId: '1:537714219373:android:55a66a89f87887b0cd6264',
    messagingSenderId: '537714219373',
    projectId: 'safegas001',
    storageBucket: 'safegas001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGApR7hvLI_8KC5TFPs_wV3z9SchOgbC8',
    appId: '1:537714219373:ios:b03f7e95b95577e9cd6264',
    messagingSenderId: '537714219373',
    projectId: 'safegas001',
    storageBucket: 'safegas001.firebasestorage.app',
    iosClientId: '537714219373-nf6inv6i8vltqem8kk2uf103rk8k829a.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoramentoGas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGApR7hvLI_8KC5TFPs_wV3z9SchOgbC8',
    appId: '1:537714219373:ios:b03f7e95b95577e9cd6264',
    messagingSenderId: '537714219373',
    projectId: 'safegas001',
    storageBucket: 'safegas001.firebasestorage.app',
    iosClientId: '537714219373-nf6inv6i8vltqem8kk2uf103rk8k829a.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoramentoGas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAmF1eF-eOJzOviCVdJK0PgWkZQJQCmkY',
    appId: '1:537714219373:web:9307e4ad7332a96ccd6264',
    messagingSenderId: '537714219373',
    projectId: 'safegas001',
    authDomain: 'safegas001.firebaseapp.com',
    storageBucket: 'safegas001.firebasestorage.app',
    measurementId: 'G-0KRGY3CTFE',
  );
}
